# Generated by Django 3.0.5 on 2021-04-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210430_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='created',
            new_name='login_time',
        ),
    ]
